export const LOAD_TRANSPORTATIONS = 'app/LOAD_TRANSPORTATIONS';
export const LOAD_TRANSPORTATIONS_SUCCESS = 'app/LOAD_TRANSPORTATIONS_SUCCESS';
export const LOAD_TRANSPORTATIONS_ERROR = 'app/LOAD_TRANSPORTATIONS_ERROR';
